#!/bin/bash

################################################################################################################
#     _____________ _________ _________ __     ___ ___  _______   __     ___ ___________________________________
#    |__\_   _____//   _____//   _____//  |_  /   |   \ \      \_/  |_  /   |   \______   \_   _____/\_   _____/
#     |  ||    __)_ \_____  \ \_____  \\   __\/    ~    \/   |   \   __\/    ~    \       _/|    __)_  |    __)_ 
#     |  ||        \/        \/        \|  |  \    Y    /    |    \  |  \    Y    /    |   \|        \ |        \
# /\__|  /_______  /_______  /_______  /|__|   \___|_  /\____|__  /__|   \___|_  /|____|_  /_______  //_______  /
# \______|       \/        \/        \/              \/         \/             \/        \/        \/         \/ 
################################################################################################################
# WHEN INJUSTICE BECOMES LAW, 
#                                RESISTANCE BECOMES DUTY
################################################################################################################
#       ___.                  __   
# _____ \_ |__   ____  __ ___/  |_ 
# \__  \ | __ \ /  _ \|  |  \   __\
#  / __ \| \_\ (  <_> )  |  /|  |  
# (____  /___  /\____/|____/ |__|  
#      \/    \/                    
################################################################################################################
# This is part of my suite of scripts that I created in order to make basic Linux tasks easier and more secure by default. This specific one is a wizard for SSH.
#
# I don't know if anyone will see this, but feel free to make any modifications to my script. 
# Feel free to contact me @ jessthnthree33@protonmail.me or @ jessthnthree33 on **Twitter**.
################################################################################################################
# TO DO!!!!!!!!!!!!!!!!!!
################################################################################################################
# - [x] Test on Debian
# - [ ] Test on Ubuntu
################################################################################################################

# Script to update the server and install docker

# Function to check if a package is installed
is_installed() {
    dpkg -s "$1" &> /dev/null
}

# Function to update system
system_update() {
    echo "Updating system packages..."
    sudo apt-get update -y && sudo apt-get upgrade -y
}

# Function to install a package
install_package() {
    if is_installed "$1"; then
        echo "$1 is already installed."
    else
        echo "$1 is not installed, installing..."
        sudo apt-get install -y "$1"
    fi
}

install_docker() {
    echo "Installing Docker..."
    sudo apt-get install -y ca-certificates curl
    sudo install -m 0755 -d /etc/apt/keyrings

    # Add Docker's GPG key
    local docker_gpg_key_url="https://download.docker.com/linux/debian/gpg"
    local keyring_path="/etc/apt/keyrings/docker.asc"
    sudo curl -fsSL "$docker_gpg_key_url" -o "$keyring_path"
    sudo chmod a+r "$keyring_path"

    # Add the Docker repository
    local repo_url="deb [arch=$(dpkg --print-architecture) signed-by=$keyring_path] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable"
    echo "$repo_url" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update

    # Install Docker packages
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    echo "Docker installation complete."
}

# Main execution starts here
system_update

# Docker Installation
install_docker

# Testing Docker installation
echo "Testing Docker installation..."
sudo docker run hello-world
echo "Installation complete. Dolphin time, baby!"
